# Generated by Django 4.1.5 on 2023-02-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('expires_in', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bearer')),
                ('indoor_bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indoor_bike', to='main.bike')),
                ('outdoor_bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_bike', to='main.bike')),
            ],
        ),
    ]
