# Generated by Django 4.1.5 on 2023-02-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_autochange_indoor_bike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearer',
            name='write_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
