# Generated by Django 4.1.5 on 2023-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bearer_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='expires_at',
            field=models.IntegerField(),
        ),
    ]
