# Generated by Django 4.1.5 on 2023-02-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='autochange_indoor_bike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='autochange_outdoor_bike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bearer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bearer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='indoor_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indoor_bike', to='main.bike'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='outdoor_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_bike', to='main.bike'),
        ),
    ]
