# Generated by Django 4.1.5 on 2023-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_defaultbikes_logging_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
