# Generated by Django 4.1.5 on 2023-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bike_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='application',
            field=models.CharField(choices=[('main', 'main'), ('autobikechange', 'autobikechange'), ('muting', 'muting'), ('maintenance', 'maintenance')], default='main', max_length=25),
        ),
    ]
