# Generated by Django 4.1.5 on 2023-02-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bearer_write_access_bike_distance_bike_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='expires_in',
            field=models.IntegerField(),
        ),
    ]
