# Generated by Django 4.1.5 on 2023-02-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_profile_autochange_indoor_bike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bearer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bearer'),
        ),
    ]
