spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    sufix: .html

  application:
    name: Bootstrap StravaTools
 
  stravatools:
    client_id: ${STRAVA_CLIENT_ID}
    client_secret: ${STRAVA_CLIENT_SECRET}

  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
      username: ${CASSANDRA_USERNAME}
      password: ${CASSANDRA_PASSWORD}
      request.timeout: 10s
      connection.connect-timeout: 10s
      connection.init-query-timeout: 10s

sendgrid_api_key: ${SENDGRID_API_KEY}
sendgrid_from_address: ${SENDGRID_FROM_ADDRESS}

astra:
  api:
    application-token: ${ASTRA_APPLICATION_TOKEN}
    database-id: ${ASTRA_DATABASE_ID}
    database-region: us-east1
    cross-region-failback: false
    grpc:
      enabled: true
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: stravatools

logging.level.org.springframework.web.client.RestTemplate: DEBUG
logging.level.com.stravatools.main: DEBUG


