# Generated by Django 4.1.5 on 2023-03-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muting', '0003_alter_muting_muteall'),
    ]

    operations = [
        migrations.AddField(
            model_name='muting',
            name='lastupdatedactivity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
