# Generated by Django 4.1.5 on 2023-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autochange_indoor_bike', models.BooleanField(default=False)),
                ('autochange_outdoor_bike', models.BooleanField(default=False)),
            ],
        ),
    ]
