# Generated by Django 4.1.5 on 2023-02-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primary', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultBikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autochange_indoor_bike', models.BooleanField(default=False)),
                ('autochange_outdoor_bike', models.BooleanField(default=False)),
                ('indoor_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indoor_bike', to='defaultbikes.bike')),
                ('outdoor_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_bike', to='defaultbikes.bike')),
            ],
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('message', models.CharField(max_length=500)),
                ('defaultbikes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defaultbikes.defaultbikes')),
            ],
        ),
    ]
