# Generated by Django 4.1.5 on 2023-02-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autochange_indoor_bike', models.BooleanField(default=False)),
                ('autochange_outdoor_bike', models.BooleanField(default=False)),
                ('indoor_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indoor_bike', to='defaultbikes.bike')),
                ('outdoor_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outdoor_bike', to='defaultbikes.bike')),
            ],
        ),
    ]
