# Generated by Django 4.1.5 on 2023-03-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('defaultbikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultbike',
            name='indoor_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indoor_bike', to='main.bike'),
        ),
        migrations.AddField(
            model_name='defaultbike',
            name='outdoor_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outdoor_bike', to='main.bike'),
        ),
    ]
