# Generated by Django 4.1.5 on 2023-02-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('defaultbikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
