# Generated by Django 4.1.5 on 2023-02-23 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defaultbikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='primary',
        ),
        migrations.AddField(
            model_name='bike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultbikes',
            name='indoor_bike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indoor_bike', to='defaultbikes.bike'),
        ),
        migrations.AlterField(
            model_name='defaultbikes',
            name='outdoor_bike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_bike', to='defaultbikes.bike'),
        ),
    ]
