# Generated by Django 4.1.5 on 2023-02-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaultbikes', '0002_remove_bike_brand_name_remove_bike_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='user',
        ),
    ]
