# Generated by Django 4.1.5 on 2023-02-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_profile_autochange_indoor_bike_and_more'),
        ('defaultbikes', '0003_remove_bike_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultBikes',
            new_name='DefaultBike',
        ),
    ]
