# Generated by Django 4.1.5 on 2023-02-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultbikes', '0004_rename_defaultbikes_defaultbike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultbike',
            name='indoor_bike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indoor_bike', to='defaultbikes.bike'),
        ),
        migrations.AlterField(
            model_name='defaultbike',
            name='outdoor_bike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outdoor_bike', to='defaultbikes.bike'),
        ),
    ]
