# Generated by Django 4.1.5 on 2023-02-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultbikes', '0005_alter_defaultbike_indoor_bike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultbike',
            name='indoor_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indoor_bike', to='defaultbikes.bike'),
        ),
        migrations.AlterField(
            model_name='defaultbike',
            name='outdoor_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outdoor_bike', to='defaultbikes.bike'),
        ),
    ]
